#!/bin/bash
javac -classpath "commons-lang3-3.5.jar:commons-cli-1.4.jar:lombok.jar:/usr/local/google/eclipse47_tintor/stable/plugins/org.junit_4.12.0.v201504281640/junit.jar" src/tintor/*/*.java src/tintor/*/*/*.java
